config/routes.rb
Rails.application.routes.draw do
  resources :clients
  get 'login', to: "login#index", as: :login
  get 'omniauth_callbacks/facebook'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/auth/facebook/callback", to: "omniauth_callbacks#facebook"
  post "/auth/developer/callback", to: "omniauth_callbacks#developer" unless Rails.env.production?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :user_signed_in?

  def require_authentication
    redirect_to login_path, alert: "" unless user_signed_in?
  end

  def current_user
    @current_user ||= User.find_by(uid: session[:user_uid]) if session[:user_uid]
  end

  def user_signed_in?
    !!current_user
  end

  def set_current_path
    session[:current_path] = request.env['PATH_INFO']
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :set_current_path
  before_action :require_authentication 

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)
    @client.user = current_user
    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Thêm thành công" }
        format.json { render :show, status: :created, location: @client }
        format.turbo_stream {flash.now[:notice] = "Thêm thành công"}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :time, :note)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_authentication

  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  protect_from_forgery except: :developer
  def facebook
    user = User.find_or_create_by(uid: auth[:uid], provider: auth[:provider]) do |user|
      user.uid = auth[:uid]
      user.provider = auth[:provider]
      user.name = auth[:info][:name]
      user.image = auth[:info][:image]
    end
    if user
      session[:user_uid] = user.uid
      redirect_to session[:current_path] || root_path
    end
  end

  def developer
    user = User.find_or_create_by(uid: auth[:uid], provider: auth[:provider]) do |user|
      user.uid = auth[:uid]
      user.provider = auth[:provider]
      user.name = auth[:info][:name]
      user.image = "#noimage" # auth[:info][:image]
    end
    if user 
      session[:user_uid] = user.uid 
      redirect_to session[:current_path] || root_path 
    end
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= client.phone %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= client.time %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= client.note %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: "Tên khách hàng" %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, placeholder: "Số điện thoại" %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.datetime_field :time, placeholder: "Thời gian" %>
  </div>

  <div>
    <%= form.label :note, style: "display: block" %>
    <%= form.text_area :note, placeholder: "Ghi chú" %>
  </div>

  <div>
    <%= form.submit "Thêm mới" %>
  </div>
<% end %>

app/views/clients/create.turbo_stream.erb
<%= turbo_stream.replace Client.new do %>
    <%= button_to "Khách hàng mới", new_client_path, method: :get %>
<% end %>

<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= turbo_frame_tag Client.new do %>
 <%= render "form", client: @client %>
<% end %>
<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/home/index.html.erb
<%= current_user.name %>
<div id="flash">
    <%= render "layouts/flash" %>
</div>
<%= turbo_frame_tag Client.new do %>
    <%= button_to "Khách hàng mới", new_client_path, method: :get %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lichcuatoi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<% if Rails.env.production? or Rails.env.test? %>
    <%= button_to "Đăng nhập với Facebook", "/auth/facebook/", method: :post, data: {turbo: false}%>
<% else %>
    <%= button_to "Đăng nhập", "/auth/developer/", method: :post, data: {turbo: false}%>
<% end %>